### ISSUE TITLE
Use contexts when logging

### ISSUE THREAD

**Issue by ash2k** [jtblin/gostatsd#10]
To consistently add relevant fields to logs, logger contexts could be used - https://github.com/Sirupsen/logrus#fields
Stuff like source IP, port and maybe something else could be added as context fields.

**Comment by jtblin** [comment]
Yes agreed. I was looking if we could create a new logger with some fields like we do with `bunuyan` in node but it doesn't look like it's possible. I wonder whether we could find another library that does that or contribute it to this lib.
